

version: '2'

services:
  redis:
    image: redis:latest

  mongo:
    image: mongo:latest

  mongo-express:
    image: mongo-express:latest
    links: 
      - mongo
    ports:
      - 8081:8081

  web:
    image: node:latest
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: "npm start"
    environment:
      - MONGO_URI=mongodb://mongo/flyn
      - PORT=3000
    ports:
      - 80:3000
    links: 
      - mongo
      - redis